### ISSUE TITLE
Status effect modifiers not applying

### ISSUE THREAD

**Issue by Warwomble** [lipefl/swade-tools#105]
Think I have found a bug in the modifiers for status effects are not being applied to the rolls. 
For instance, in the screen grab attached the Giant Mosquito is Vulnerable so the Mighty Grog should get +2 to hit but this is not being applied.

![Screenshot 2022-02-16 at 10 40 18](https://user-images.githubusercontent.com/99798988/154239316-84e0a272-1bd1-4705-8f1c-30fa708f1bdb.png)
.

**Comment by lipefl** [comment]
You must click in the (?) icon to see target modifiers. It's not directly applied to the roll because it depends on the target. There's also an option to "always show the situational modifiers", so this (?) will always be "clicked". I'll close the issue, feel free to re-open if you have any questions.

**Comment by Warwomble** [comment]
Thanks very much
