### ISSUE TITLE
[Feature] Enhance roll windows

### ISSUE THREAD

**Issue by sladecraven** [lipefl/swade-tools#138]
In the latest SWADE system release, the roll windows allow many options for skills : 

![image](https://user-images.githubusercontent.com/1085008/167312402-bf693166-6dc0-4786-8d3a-9159c45d7a1b.png)

It would be great to have such "pre-defined" values in the roll windows for weapons and powers when using SWADE Tools.

**Comment by lipefl** [comment]
I'll be honest with you. I had a lot of problems with this "many options" for modifiers in all my games with all players. That's why i added "Simple Trait Rolls" option for SWADE Tools by default. 
I would add as an option if it's not too much trouble, but it's not the case. It would be a lot of work for something i don't think would help at all. The weapon/power window already has a lot of options.
