### ISSUE TITLE
custom define the relation of size and token's width&height

### ISSUE THREAD

**Issue by EternalRider** [lipefl/swade-tools#184]
just 2x2 for 4~7 size and even 4x4 to 20 size is too weak for expressiveness.
And it doesn't conform to the rules book about body shape and body length & height.
According to the description in the rule book, a creature of size 12 should be 100 feet long, but the size of 4*4 seems to be only 20 feet.
it should be a way to let user define the tokensize auto change, or just offer a checkbox to close this function.

**Comment by lipefl** [comment]
If you don't like it, you can change the token width/height after defining the size. The automation is there just to simplify the process.

Just to let you know, since there's no "official" rule about this in SWADE edition, the width/height chosen are based on this text from Super Powers Companion (the old edition), on power Growth.

"Between Size +4 to +7, the character is considered Large, at +8 to +10 he’s Huge, and at +11 and higher he’s Gargantuan. See Savage Worlds for specific effects. If using miniatures, Large characters occupy a 2” square, Huge 3”, and Gargantuan 4” plus another inch square per additional level."

In SWADE Tools, it starts at 1x1 and every "scale up" will increase 1 (to 2x2, 3x3, etc). 

Btw, the 100' doesnt mean the creature is 100' long (it could be its height). So, as far as i know, the GM is free to change this according to the creature.
