### ISSUE TITLE
Can't apply Shaken/Damage to multiple targets

### ISSUE THREAD

**Issue by DariusArgent** [lipefl/swade-tools#195]
How to reproduce it:
Select multiple tokens and assign them as targets
Roll for damage with anything
When the results come in the chat you can only click one target to apply shaken/damage. When you click another target nothing happens.

**Comment by lipefl** [comment]
Hi, i was testing and i found out this is the intended behaviour. Since we never use the same damage roll against multiple targets in swade core, this is to avoid accidentally clicking on another target.
I can add an option to allow to use the same damage roll for multiple targets. Would it solve it for you?

**Comment by DariusArgent** [comment]
That would be great, thank you

**Comment by lipefl** [comment]
Now it's possible to do it in v1.11.0 (no need to change an option). Please update.
