### ISSUE TITLE
Cover

### ISSUE THREAD

**Issue by Neurochimp** [lipefl/swade-tools#213]
Hi.

This is more so a research ask. Are there any other item types that have cover besides shields?

Is there a way to set an active effect with cover? Tried system.stats.cover.value as a guess and didn't work.

Thanks

**Comment by lipefl** [comment]
I dont think there's other items with cover. Nor there's a active effect for it. But i'm not sure. I think you can have this answer in discord.
But... you can create a shield item, give it cover and equip/unequip as activate/deactivate. That's what originated the idea to implement in the module: to simulate "Light/Medium/Heavy Cover" or "Deflection" power effect. See #209 

The text in the config section is just because the module doesn't look for type "shield", just items that have cover and are equipped (in case that's available in the future).

**Comment by Neurochimp** [comment]
Thank you! I figured as much but wondered during implementation whether you had any cases from something other than a shield.

**Comment by Neurochimp** [comment]
Even if I can't make it as an effect, equipping a shield placeholder does make my life easier for a guy in my Sunday game that has a +1 dodge bonus since cover & dodge roughly do the same thing in this regard & can't overlap. And it will help the guys with Deflection in my Pathfinder game too.
