### ISSUE TITLE
Used RoF3 weapon but only 2 hits were recognized.

### ISSUE THREAD

**Issue by RandyLyne** [lipefl/swade-tools#22]
As the title says.
![image](https://user-images.githubusercontent.com/77080531/107086466-aa639700-67bf-11eb-9a46-8f0596ca0254.png)

**Comment by lipefl** [comment]
RoF rolls are not calculated. Since it's not possible to define wich die will affect the target(s) (or will make it more complicated than intended). The info is just for you to choose and roll damage (Hit or Raise).
I tried to explain this with the text "For RoF, hit/raise..." but it's probably not that clear.

**Comment by RandyLyne** [comment]
Oh, i see. Since i rolled a 4 and an 8 it really confused me.
