### ISSUE TITLE
Animations show up on damage roll instead of skill roll

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#229]
I use Automated Animations for attacks and powers. When I use the SWADE core system without SWADE Tools, the animation is shown with an (successful) action or power roll:
![Power_SWADE_Core](https://github.com/lipefl/swade-tools/assets/119852651/1dd7bee0-4f8e-47ff-85d3-77df89764af9)

But when I use SWADE Tools, nothing happens at the action roll:
![Power_SWADE_Tools_1](https://github.com/lipefl/swade-tools/assets/119852651/af25da97-f8a2-4c0d-8d01-c50ac03ac9d2)

Instead the animation is shown with the damage roll (if I at least shaken the target):
![Power_SWADE_Tools_2](https://github.com/lipefl/swade-tools/assets/119852651/25dee614-860c-4157-b99a-da7c2d3231d2)

Since I love the animations showing up more often, I prefer them on the action role like with SWADE Core. Is it possible to change the behaviour of SWADE Tools, so that the animations show up on the action roll as well? Or to offer an option for when to show the animations?

- Foundry VTT: 11.302
- Swade System: swade 3.0.4
- SWADE Tools: 1.13.0
- Sequencer 3.0.11
- Automated Animations 4.2.60
- Savage Pathfinder Encanced 0.6 (I use the animation autoload config from it)
- Browser: Google Chrome

**Comment by lipefl** [comment]
I investigated it and i can't find what's triggering the animation. For me, it seems to be a bug, for some reason it doesn't trigger in skill item roll, but i does on damage. In my tests, SWADE system (without SWADE Tools) triggers everytime (skill and damage).

Anyway, i'm not that familiar with animation modules and how they work, if i need to introduce some code or specific tag, let me know and i'll be glad to do it and add more option on how they are shown. But i cant seem to find a documentation on this, maybe i am confused because it's a lot of modules. Any help will be appreciated.

**Comment by Vogliadicone** [comment]
There's a new option in AA which allows you to specify where AA should play the animation: AA Settings > Launch Menu > Settings > Savage Worlds Adventure Edition > When to play animations. It wasn't set up correctly in my system. After I corrected it, it also works with SWADE Tools. Sorry for the false alarm & thanks for your time investigating it!
