### ISSUE TITLE
Hidden/Private rolls not working

### ISSUE THREAD

**Issue by simondw2000** [lipefl/swade-tools#243]
Using the options for Private GM Roll, Blind GM Roll, or Self Roll do not change how the roll is diaplyed with SWADE Tools active. The rolls are the same as public.
I can't see any options in the settings that I think would affect this, so apologies if I have missed anything there.

I have tried disabling all modules except for SWADE Tools and the issue persists.

Foundry version: 11.305
SWADE version: 3.0.4
SWADE Tools version: 1.13.4

I am not sure if this has previously worked with SWADE Tools or not.

If possible it would be ideal to hide the rolls as expected but have an option to allow players to see the 'Apply Damage' and 'Soak Damage' buttons.

PS. Thanks for the great module!!

**Comment by lipefl** [comment]
Fixed in v1.14.0
Only compatible with SWADE system 3.1.x (please update SWADE system as well)

It'll use whatever you selected in the foundry chat selectable

![image](https://github.com/lipefl/swade-tools/assets/10639148/beabc307-6fc9-421d-ad32-f148c9aab795)

The asked feature is hard to do since Apply,Soak, etc are directly tied to the roll being shown.
