### ISSUE TITLE
Maestro + Item Track = double sound

### ISSUE THREAD

**Issue by smoothingplane** [lipefl/swade-tools#36]
When a weapon is linked with Maestro (using item track), either if you make the hit check or if you roll damage, the sound activates, causing a double sound in a row.
But it's also true that if someone doesn't need to roll the ability to hit, the sound should sound the same by just rolling damage.
Maybe it could be disabled when using SWADE Tools target function.
Example:
By clicking on the skill the sound starts and then clicking on "Enemy: Hit" to roll the damage the sound does not start.
Is it possible to make it work like that?

**Comment by lipefl** [comment]
I'm not used to Maestro, so it was really a "question" for me. I deliberatly choose to put it in both (skill and damage). I can put only in skill roll, it'll fix the "double sound", but it will not activate the sound when using damage from dialog.

**Comment by smoothingplane** [comment]
Maybe you can put an option in settings for choose which of two method you want to use.

**Comment by lipefl** [comment]
I saw some videos about Maestro and decided to put it in skill, since it's how it's used in other systems. 
The setting thing was a nice idea, but there's no setting in Maestro about damage rolls, i think it'll be confusing to put it in Swade Tools. If they update Maestro with something like this, it'll be fine to use it.
