### ISSUE TITLE
Handling of Wild Attack and associated Vulnerable status

### ISSUE THREAD

**Issue by steveculshaw** [lipefl/swade-tools#45]
Is there anyway to handle Wild Attack (p.109) and it's associated Vulnerable status which is until the end of the characters **next** turn ?

The automatic removal of Vulnerable is happening at the end of the characters current turn, so we have to remember to re-apply the Vulnerable status

**Comment by lipefl** [comment]
Swade Tools will only remove Vulnerable/Distracted if the char starts the turn with it. So if you mark these status during the char turn, it'll only be removed in the next round. The only case scenario i can see what you mentioned it's if the char was already Vulnerable at the start, in this case it'll be removed anyway and you'll have to remember to re-apply.

I'll close this issue, but feel free to open it again if you have any problems or ideas on how to improve it.

**Comment by grendel111111** [comment]
It does the same for me. If you wild attack 2 turns in a row (or you were vulnerable at the start of the round because you are recovering from stunned) then the vulnerable condition goes away instead of staying till the next round.  I see that at the end of the round it checks if a flag is on that tells that you were vulnerable at the start of the round or not. So if you were vulnerable it sets to yes, if not, no. Then at the end it checks the current state of the flag. Would it be possible to put a line into a macro which adds the wild attack condition, and sets the "vulnerable at start of turn" flag to "no". Then when it gets to the end of the round it looks and thinks that it wasn't on at the start of the round and so doesn't turn it off?  I tried to see where the flag was to change it, but can't find it. Am I chasing something that won't work?

**Comment by lipefl** [comment]
1 - The flag you're looking for is inside the combat -> combatant, called swade-tools[removeVulnerable]. I think i can put a button in melee options "Wild Attack" that will "force" the Vulnerable status to stay at the end of turn.

2 - I tested what you said about end of round, and you're right. Probably a bug, i'll look into that too. Thanks!

**Comment by lipefl** [comment]
I added a Wild Attack button for melee... Also solved the "end of round" problem. Hope it helps. Update to 1.3.3. Thanks!

**Comment by steveculshaw** [comment]
@lipefl Nice one ... 
Can you please explain the logic in how the Wild Attack button works?
I've installed v1.3.3 and got the button.
Token makes the Wild Attack, and becomes Vulnerable 
But going through multiple turns, and the Vulnerable doesn't automatically disappear like it used to ?

**Comment by lipefl** [comment]
@steveculshaw The wild attack only gives the bonus and "force" the Vulnerable status not to be removed this turn (even if the char was already Vulnerable). The next round everything should work as normal. I tested here and it's working fine.

**Comment by grendel111111** [comment]
Thanks. The wild attack works great. The end of round effect is still happening.

**Comment by lipefl** [comment]
@grendel111111 it was working. It must be something i did after... Sorry. I'll reopen the issue and investigate.

**Comment by lipefl** [comment]
Problem with "end of round" fixed in v1.3.4
